apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: frontend
          image: ghcr.io/podkrepi-bg/frontend
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          env:
            - name: NODE_ENV
              value: production
            - name: TARGET_ENV
              value: production
            - name: APP_ENV
              value: production
            - name: APP_PORT
              value: '3040'
            - name: REST_API_PORT
              value: '80'
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: config-web
                  key: app-url
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: config-web
                  key: app-url
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets-web
                  key: next-auth-secret
            - name: GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: secrets-web
                  key: google-id
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets-web
                  key: google-secret
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: config-web
                  key: api-url
            - name: IMAGE_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-web
                  key: image-host
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config-web
                  key: url
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config-web
                  key: realm
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config-web
                  key: client-id
          ports:
            - containerPort: 3040
          resources:
            limits:
              memory: 350Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3040
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3040
            initialDelaySeconds: 5
            periodSeconds: 5
