version: '3.7'
# Override service props from main `docker-compose.yml`
services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: ${TARGET_ENV?}
      args:
        NODE_ENV: ${NODE_ENV?}
    ports:
      - '${APP_PORT?}:3040'
    volumes:
      # Local:Container mounting points
      - ./src:/app/src
      - ./public:/app/public
      - /app/.next
      - /app/node_modules

  api:
    build:
      context: ./backend/contact
      dockerfile: ./Dockerfile
      target: ${TARGET_ENV?}
    environment:
      DEBUG: 'true'
    ports:
      - '${REST_API_PORT?}:5000'
    volumes:
      - ./backend/contact:/app
      - /app/dist

  roach-lb:
    ports:
      - '${DB_PORT?}:26257'
      - '3080:8080'
      - '3081:8081'

  flyway:
    build:
      context: .
      dockerfile: ./flyway/Dockerfile
    volumes:
      - ./db/migrations:/flyway/sql
