name: Build contact

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/podkrepi-bg/go-devcontainer:v1.0.0
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        working-directory: backend/contact
        run: task lint

      - name: Test
        working-directory: backend/contact
        run: task test

      - name: Build
        working-directory: backend/contact
        run: task build
        
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: backend/contact
          push: false